CREATE TABLE IF NOT EXISTS tracking
(
    chat_id BIGINT REFERENCES chats(id) ON DELETE CASCADE NOT NULL,
    link_id BIGINT REFERENCES links(id) ON DELETE RESTRICT NOT NULL,
    PRIMARY KEY (chat_id, link_id)
);
