name: Bot CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'
      - 'bot.Dockerfile'
      - 'pom.xml'
  pull_request:
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'
      - 'bot.Dockerfile'
      - 'pom.xml'


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project with Maven
        run: mvn package -pl bot -am

      - name: Build Docker image
        run: docker build --build-arg bot_token=${{ secrets.BOT_TOKEN }} -f bot.Dockerfile -t bot .

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push bot image to the Container registry
        run: docker push ghcr.io/${{github.actor}}/bot:latest
