name: Bot CI

on:
  push:
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'
      - 'bot.Dockerfile'
      - 'pom.xml'
  pull_request:
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'
      - 'bot.Dockerfile'
      - 'pom.xml'


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package -pl bot -am
