name: Scrapper CI

on:
  push:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'migrations/**'
      - 'link-parser/**'
      - '.github/workflows/scrapper.yml'
      - 'scrapper.Dockerfile'
      - 'docker-compose.yml'
      - 'pom.xml'
  pull_request:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'migrations/**'
      - 'link-parser/**'
      - '.github/workflows/scrapper.yml'
      - 'scrapper.Dockerfile'
      - 'docker-compose.yml'
      - 'pom.xml'


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - name: Build Docker image
        run: docker build -f scrapper.Dockerfile -t scrapper .
