name: Scrapper CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'migrations/**'
      - 'link-parser/**'
      - '.github/workflows/scrapper.yml'
      - 'scrapper.Dockerfile'
      - 'docker-compose.yml'
      - 'pom.xml'
  pull_request:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'migrations/**'
      - 'link-parser/**'
      - '.github/workflows/scrapper.yml'
      - 'scrapper.Dockerfile'
      - 'docker-compose.yml'
      - 'pom.xml'

env:
  REGISTRY: ghcr.io
  MODULE_NAME: scrapper
  IMAGE_VERSION: latest

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Scrapper Jooq
        run: mvn package -pl scrapper-jooq -am

      - name: Run Scrapper Jooq JAR
        run: java -jar scrapper-jooq/target/scrapper-jooq-1.0-SNAPSHOT.jar

      - name: Build with Maven
        run: mvn package -pl ${{ env.MODULE_NAME }} -am

      - name: Change String Case
        id: lw-step
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Build Docker image
        run: | 
          docker build -f ${{ env.MODULE_NAME }}.Dockerfile -t 
          ${{ env.REGISTRY }}/${{ steps.lw-step.outputs.lowercase }}/${{ env.MODULE_NAME }}:${{ env.IMAGE_VERSION }} .

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push scrapper image to the Container registry
        run: |
          docker push 
          ${{ env.REGISTRY }}/${{ steps.lw-step.outputs.lowercase }}/${{ env.MODULE_NAME }}:${{ env.IMAGE_VERSION }}
